server:
  port : 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: users

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:../subdirectory/testdb #url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

message : I'm from users properties file